import { faker } from "@faker-js/faker"

import { ICategory } from "./initialState"

export const reducers = {
  restoreData: (state: ICategory[]) => {
    state = Array.from({ length: 4 }, () => ({
      id: faker.string.uuid(),
      title: faker.helpers.arrayElement([
        "Покупки",
        "Транспорт",
        "Связь",
        "Подарки",
        "Переводы",
        "Здоровье",
        "Уход",
        "Такси",
        "Досуг",
        "Кино",
        "Развлечения",
        "Путешествия",
        "Билеты",
        "Продукты",
        "Вода",
        "Свет",
        "Отопление",
        "Аренда",
        "Квартира",
        "Игры",
      ]),
      icon: faker.helpers.arrayElement([
        "home",
        "favorite",
        "shopping_cart",
        "calendar_month",
        "shopping_basket",
        "restaurant",
        "local_shipping",
        "flight",
        "celebration",
        "local_cafe",
        "fastfood",
        "local_taxi",
        "local_pizza",
        "directions_bus_filled",
        "nightlife",
        "icecream",
        "hardware",
        "local_movies",
        "event_available",
        "phone_callback",
        "phone_iphone",
        "checkroom",
        "fitness_center",
        "child_friendly",
        "light",
      ]),
      color: faker.helpers.arrayElement([
        "Aqua",
        "Teal",
        "Blue",
        "Navy",
        "Yellow",
        "Olive",
        "Lime",
        "Green",
        "Fuchsia",
        "Purple",
        "Red",
        "Maroon",
        "SandyBrown",
        "Goldenrod",
        "DarkGoldenRod",
        "Peru",
        "Chocolate",
        "SaddleBrown",
        "Sienna",
        "Brown",
        "Maroon",
        "Violet",
        "Orchid",
        "Fuchsia",
        "Magenta",
        "MediumOrchid",
        "MediumPurple",
        "BlueViolet",
        "DarkViolet",
        "DarkOrchid",
        "DarkMagenta",
        "Purple",
        "Indigo",
        "SlateBlue",
        "DarkSlateBlue",
        "IndianRed	#CD5C5C	205, 92, 92",
        "LightCoral",
        "Salmon",
        "DarkSalmon",
        "LightSalmon",
        "Crimson",
        "Red",
        "FireBrick",
        "DarkRed",
        "GreenYellow",
        "Chartreuse",
        "LawnGreen",
        "Lime",
        "LimeGreen",
        "PaleGreen",
        "LightGreen",
        "MediumSpringGreen",
        "SpringGreen",
        "MediumSeaGreen",
        "SeaGreen",
        "ForestGreen",
        "Green",
        "DarkGreen",
        "YellowGreen",
        "OliveDrab",
        "Olive",
        "DarkOliveGreen",
      ]),
    }))

    return state
  },
}
